/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apprankinglist;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    private Jugador jugador = null; // jugador principal
    private ArrayList<Jugador> jugadores= new ArrayList<>();  // lista de jugadores
    private Random rnd = new Random();
   

    public view() {
        initComponents();
        this.setLocationRelativeTo(this);
        rsscalelabel.RSScaleLabel.setScaleLabel(background, "src/images/background.jpg");
    }

    // Rellenamos la lista con datos falsos
    public void rellenarLista() {
        String nombresFalsos[] = {
            "Leanne Graham",
            "Ervin Howell",
            "Clementine Bauch",
            "Patricia Lebsack",
            "Chelsey Dietrich",
            "Mrs. Dennis Schulist",
            "Kurtis Weissnat",
            "Nicholas Runolfsdottir V",
            "Glenna Reichert",
            "Clementina DuBuque"
        };

        

        for (String nombre : nombresFalsos) {
            int puntajeAleatorio = rnd.nextInt(2000 - 1000 + 1) + 1000; // puntaje aleatorio entre 2000 y 1000
            jugadores.add(new Jugador(nombre, puntajeAleatorio));
        }
    }

    
    public void alternarEstadoDeBotones(boolean inicial){
        btnIniciar.setEnabled(inicial);
        btnVerRanking.setEnabled(!inicial);
    }
    
    public void ordenarRanking(){
        
        jugadores.sort(Comparator.comparing(Jugador::getPuntaje).reversed());
    }
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnVerRanking = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese su nombre de jugador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RANKING LIST");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        txtNombre.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        txtNombre.setToolTipText("Ingrese su nombre de jugador aqui");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 310, -1));

        btnVerRanking.setBackground(new java.awt.Color(51, 204, 0));
        btnVerRanking.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btnVerRanking.setText("VER RANKING");
        btnVerRanking.setEnabled(false);
        btnVerRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRankingActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 40));

        btnIniciar.setBackground(new java.awt.Color(51, 204, 0));
        btnIniciar.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btnIniciar.setText("INICIAR PARTIDA");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 40));

        background.setOpaque(true);
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRankingActionPerformed
        // TODO add your handling code here:
        // mostrando lista de jugadores por consola
        ordenarRanking();
        ViewRanking newFrame = new ViewRanking(jugadores,jugador);
        
        newFrame.setVisible(true);
        alternarEstadoDeBotones(true);
        this.dispose();
    }//GEN-LAST:event_btnVerRankingActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe de ingresar su nombre de jugador");
        } else if (nombre.length() < 4) {
            JOptionPane.showMessageDialog(this, "El nombre del jugador debe de contener al menos 4 carácteres");
        } else {

            rellenarLista();
            int puntajeAleatorio = rnd.nextInt(2000 - 1000 + 1) + 1000; // puntaje aleatorio entre 2000 y 1000
            jugador = new Jugador(nombre, puntajeAleatorio);
            
            jugadores.add(jugador); // Agregamos el jugador a la lista
            alternarEstadoDeBotones(false);
            
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnVerRanking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
